cc_binary(
    name = "array_exec",
    srcs = ["main.cpp"],
    deps = [
        "//sorted_and_rotated_array_search:search",
        "//array_rotation:array_rotation",
        "//rearrangement:rearrangement",
    ],
    copts = ["-std=c++14"],
)