# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "rearrangement",
    hdrs = ["rearrangement.h"],
    srcs = ["rearrangement.cpp"],
    visibility = ["//:__pkg__"],
)