# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "search",
    srcs = ["search.hpp"],
    visibility = ["//:__pkg__"],
)